#ifndef ECAMERAMODES_H
#define ECAMERAMODES_H

//! Camera Modes
enum E_CAMERA_MODE
{
    ECM_FREE_MODE = 0,
    ECM_FOLLOW_PLAYER = 1,
    ECM_HORIZONTALSCROLLER = 2,
    ECM_VERTICALSCROLLER = 3,
    ECM_PATHSCROLLER = 4
};

#endif // ECAMERAMODES_H
