#ifndef GLFW_EVENTTYPES_H
#define GLFW_EVENTTYPES_H

// TODO: Comment me properly
enum GLFW_EventTypes
{
    GLFW_NULL_EVENT,
    GLFW_KEYBOARD_EVENT,
    GLFW_KEYBOARD_UNICODE_EVENT,
    GLFW_MOUSE_BUTTON_EVENT,
    GLFW_MOUSE_ENTER_EVENT,
    GLFW_MOUSE_SCROLL_EVENT
};

#endif // GLFW_EVENTTYPES_H
